final List<Map<String, String>> races = [
  {
    'round': '1',
    'country': 'Australia',
    'flagUrl': 'https://flagcdn.com/w80/au.png',
    'grandPrix': 'Australian Grand Prix',
    'date': '14–16 Mar',
  },
  {
    'round': '2',
    'country': 'China',
    'flagUrl': 'https://flagcdn.com/w80/cn.png',
    'grandPrix': 'Chinese Grand Prix',
    'date': '21–23 Mar',
  },
  {
    'round': '3',
    'country': 'Japan',
    'flagUrl': 'https://flagcdn.com/w80/jp.png',
    'grandPrix': 'Japanese Grand Prix',
    'date': '04–06 Apr',
  },
  {
    'round': '4',
    'country': 'Bahrain',
    'flagUrl': 'https://flagcdn.com/w80/bh.png',
    'grandPrix': 'Bahrain Grand Prix',
    'date': '11–13 Apr',
  },
  {
    'round': '5',
    'country': 'Saudi Arabia',
    'flagUrl': 'https://flagcdn.com/w80/sa.png',
    'grandPrix': 'Saudi Arabian Grand Prix',
    'date': '18–20 Apr',
  },
  {
    'round': '6',
    'country': 'USA',
    'flagUrl': 'https://flagcdn.com/w80/us.png',
    'grandPrix': 'Miami Grand Prix',
    'date': '02–04 May',
  },
  {
    'round': '7',
    'country': 'Italy',
    'flagUrl': 'https://flagcdn.com/w80/it.png',
    'grandPrix': 'Emilia‑Romagna Grand Prix',
    'date': '16–18 May',
  },
  {
    'round': '8',
    'country': 'Monaco',
    'flagUrl': 'https://flagcdn.com/w80/mc.png',
    'grandPrix': 'Monaco Grand Prix',
    'date': '23–25 May',
  },
  {
    'round': '9',
    'country': 'Spain',
    'flagUrl': 'https://flagcdn.com/w80/es.png',
    'grandPrix': 'Spanish Grand Prix',
    'date': '30 May–1 Jun',
  },
  {
    'round': '10',
    'country': 'Canada',
    'flagUrl': 'https://flagcdn.com/w80/ca.png',
    'grandPrix': 'Canadian Grand Prix',
    'date': '13–15 Jun',
  },
  {
    'round': '11',
    'country': 'Austria',
    'flagUrl': 'https://flagcdn.com/w80/at.png',
    'grandPrix': 'Austrian Grand Prix',
    'date': '27–29 Jun',
  },
  {
    'round': '12',
    'country': 'Great Britain',
    'flagUrl': 'https://flagcdn.com/w80/gb.png',
    'grandPrix': 'British Grand Prix',
    'date': '04–06 Jul',
  },
  {
    'round': '13',
    'country': 'Belgium',
    'flagUrl': 'https://flagcdn.com/w80/be.png',
    'grandPrix': 'Belgian Grand Prix',
    'date': '25–27 Jul',
  },
  {
    'round': '14',
    'country': 'Hungary',
    'flagUrl': 'https://flagcdn.com/w80/hu.png',
    'grandPrix': 'Hungarian Grand Prix',
    'date': '01–03 Aug',
  },
  {
    'round': '15',
    'country': 'Netherlands',
    'flagUrl': 'https://flagcdn.com/w80/nl.png',
    'grandPrix': 'Dutch Grand Prix',
    'date': '29–31 Aug',
  },
  {
    'round': '16',
    'country': 'Italy',
    'flagUrl': 'https://flagcdn.com/w80/it.png',
    'grandPrix': 'Italian Grand Prix',
    'date': '05–07 Sep',
  },
  {
    'round': '17',
    'country': 'Azerbaijan',
    'flagUrl': 'https://flagcdn.com/w80/az.png',
    'grandPrix': 'Azerbaijan Grand Prix',
    'date': '19–21 Sep',
  },
  {
    'round': '18',
    'country': 'Singapore',
    'flagUrl': 'https://flagcdn.com/w80/sg.png',
    'grandPrix': 'Singapore Grand Prix',
    'date': '03–05 Oct',
  },
  {
    'round': '19',
    'country': 'USA',
    'flagUrl': 'https://flagcdn.com/w80/us.png',
    'grandPrix': 'United States Grand Prix',
    'date': '17–19 Oct',
  },
  {
    'round': '20',
    'country': 'Mexico',
    'flagUrl': 'https://flagcdn.com/w80/mx.png',
    'grandPrix': 'Mexico City Grand Prix',
    'date': '24–26 Oct',
  },
  {
    'round': '21',
    'country': 'Brazil',
    'flagUrl': 'https://flagcdn.com/w80/br.png',
    'grandPrix': 'São Paulo Grand Prix',
    'date': '07–09 Nov',
  },
  {
    'round': '22',
    'country': 'USA',
    'flagUrl': 'https://flagcdn.com/w80/us.png',
    'grandPrix': 'Las Vegas Grand Prix',
    'date': '20–22 Nov',
  },
  {
    'round': '23',
    'country': 'Qatar',
    'flagUrl': 'https://flagcdn.com/w80/qa.png',
    'grandPrix': 'Qatar Grand Prix',
    'date': '28–30 Nov',
  },
  {
    'round': '24',
    'country': 'UAE',
    'flagUrl': 'https://flagcdn.com/w80/ae.png',
    'grandPrix': 'Abu Dhabi Grand Prix',
    'date': '05–07 Dec',
  },
];
