List<Map<String, String>> get scheduleData {
  return [
    // 1 • Australia (Melbourne)
    {
      'date': '14',
      'month': 'Mar',
      'startTime': '12:30',
      'endTime': '13:30',
      'session': 'Free Practice 1',
    },
    {
      'date': '14',
      'month': 'Mar',
      'startTime': '16:00',
      'endTime': '17:00',
      'session': 'Free Practice 2',
    },
    {
      'date': '15',
      'month': 'Mar',
      'startTime': '12:30',
      'endTime': '13:30',
      'session': 'Free Practice 3',
    },
    {
      'date': '15',
      'month': 'Mar',
      'startTime': '16:00',
      'endTime': '17:00',
      'session': 'Qualifying',
    },
    {
      'date': '16',
      'month': 'Mar',
      'startTime': '15:00',
      'endTime': '17:00',
      'session': 'Race',
    },

    // 2 • China (Shanghai) – Sprint weekend
    {
      'date': '21',
      'month': 'Mar',
      'startTime': '11:30',
      'endTime': '12:30',
      'session': 'Free Practice 1',
    },
    {
      'date': '21',
      'month': 'Mar',
      'startTime': '15:30',
      'endTime': '16:30',
      'session': 'Free Practice 2',
    },
    {
      'date': '21',
      'month': 'Mar',
      'startTime': '15:30',
      'endTime': '16:30',
      'session': 'Sprint Qualifying',
    },
    {
      'date': '22',
      'month': 'Mar',
      'startTime': '11:00',
      'endTime': '11:30',
      'session': 'Sprint',
    },
    {
      'date': '22',
      'month': 'Mar',
      'startTime': '15:00',
      'endTime': '16:00',
      'session': 'Qualifying',
    },
    {
      'date': '23',
      'month': 'Mar',
      'startTime': '15:00',
      'endTime': '17:00',
      'session': 'Race',
    },

    // 3 • Japan (Suzuka)
    {
      'date': '04',
      'month': 'Apr',
      'startTime': '11:30',
      'endTime': '12:30',
      'session': 'Free Practice 1',
    },
    {
      'date': '04',
      'month': 'Apr',
      'startTime': '15:00',
      'endTime': '16:00',
      'session': 'Free Practice 2',
    },
    {
      'date': '05',
      'month': 'Apr',
      'startTime': '11:30',
      'endTime': '12:30',
      'session': 'Free Practice 3',
    },
    {
      'date': '05',
      'month': 'Apr',
      'startTime': '15:00',
      'endTime': '16:00',
      'session': 'Qualifying',
    },
    {
      'date': '06',
      'month': 'Apr',
      'startTime': '14:00',
      'endTime': '16:00',
      'session': 'Race',
    },

    // 4 • Bahrain (Sakhir)
    {
      'date': '11',
      'month': 'Apr',
      'startTime': '14:30',
      'endTime': '15:30',
      'session': 'Free Practice 1',
    },
    {
      'date': '11',
      'month': 'Apr',
      'startTime': '18:00',
      'endTime': '19:00',
      'session': 'Free Practice 2',
    },
    {
      'date': '12',
      'month': 'Apr',
      'startTime': '15:30',
      'endTime': '16:30',
      'session': 'Free Practice 3',
    },
    {
      'date': '12',
      'month': 'Apr',
      'startTime': '19:00',
      'endTime': '20:00',
      'session': 'Qualifying',
    },
    {
      'date': '13',
      'month': 'Apr',
      'startTime': '18:00',
      'endTime': '20:00',
      'session': 'Race',
    },

    // 5 • Saudi Arabia (Jeddah)
    {
      'date': '18',
      'month': 'Apr',
      'startTime': '16:30',
      'endTime': '17:30',
      'session': 'Free Practice 1',
    },
    {
      'date': '18',
      'month': 'Apr',
      'startTime': '20:00',
      'endTime': '21:00',
      'session': 'Free Practice 2',
    },
    {
      'date': '19',
      'month': 'Apr',
      'startTime': '16:30',
      'endTime': '17:30',
      'session': 'Free Practice 3',
    },
    {
      'date': '19',
      'month': 'Apr',
      'startTime': '20:00',
      'endTime': '21:00',
      'session': 'Qualifying',
    },
    {
      'date': '20',
      'month': 'Apr',
      'startTime': '20:00',
      'endTime': '22:00',
      'session': 'Race',
    },

    // 6 • Miami (Sprint)
    {
      'date': '02',
      'month': 'May',
      'startTime': '12:30',
      'endTime': '13:30',
      'session': 'Free Practice 1',
    },
    {
      'date': '02',
      'month': 'May',
      'startTime': '16:30',
      'endTime': '17:30',
      'session': 'Sprint Qualifying',
    },
    {
      'date': '03',
      'month': 'May',
      'startTime': '12:00',
      'endTime': '12:30',
      'session': 'Sprint',
    },
    {
      'date': '03',
      'month': 'May',
      'startTime': '16:00',
      'endTime': '17:00',
      'session': 'Qualifying',
    },
    {
      'date': '04',
      'month': 'May',
      'startTime': '16:00',
      'endTime': '18:00',
      'session': 'Race',
    },

    // 7 • Emilia‑Romagna (Imola)
    {
      'date': '16',
      'month': 'May',
      'startTime': '13:30',
      'endTime': '14:30',
      'session': 'Free Practice 1',
    },
    {
      'date': '16',
      'month': 'May',
      'startTime': '17:00',
      'endTime': '18:00',
      'session': 'Free Practice 2',
    },
    {
      'date': '17',
      'month': 'May',
      'startTime': '12:30',
      'endTime': '13:30',
      'session': 'Free Practice 3',
    },
    {
      'date': '17',
      'month': 'May',
      'startTime': '16:00',
      'endTime': '17:00',
      'session': 'Qualifying',
    },
    {
      'date': '18',
      'month': 'May',
      'startTime': '15:00',
      'endTime': '17:00',
      'session': 'Race',
    },

    // 8 • Monaco
    {
      'date': '23',
      'month': 'May',
      'startTime': '13:30',
      'endTime': '14:30',
      'session': 'Free Practice 1',
    },
    {
      'date': '23',
      'month': 'May',
      'startTime': '17:00',
      'endTime': '18:00',
      'session': 'Free Practice 2',
    },
    {
      'date': '24',
      'month': 'May',
      'startTime': '12:30',
      'endTime': '13:30',
      'session': 'Free Practice 3',
    },
    {
      'date': '24',
      'month': 'May',
      'startTime': '16:00',
      'endTime': '17:00',
      'session': 'Qualifying',
    },
    {
      'date': '25',
      'month': 'May',
      'startTime': '15:00',
      'endTime': '17:00',
      'session': 'Race',
    },

    // 9 • Spain (Barcelona)
    {
      'date': '30',
      'month': 'May',
      'startTime': '13:30',
      'endTime': '14:30',
      'session': 'Free Practice 1',
    },
    {
      'date': '30',
      'month': 'May',
      'startTime': '17:00',
      'endTime': '18:00',
      'session': 'Free Practice 2',
    },
    {
      'date': '31',
      'month': 'May',
      'startTime': '12:30',
      'endTime': '13:30',
      'session': 'Free Practice 3',
    },
    {
      'date': '31',
      'month': 'May',
      'startTime': '16:00',
      'endTime': '17:00',
      'session': 'Qualifying',
    },
    {
      'date': '01',
      'month': 'Jun',
      'startTime': '15:00',
      'endTime': '17:00',
      'session': 'Race',
    },

    // 10 • Canada (Montreal)
    {
      'date': '13',
      'month': 'Jun',
      'startTime': '13:30',
      'endTime': '14:30',
      'session': 'Free Practice 1',
    },
    {
      'date': '13',
      'month': 'Jun',
      'startTime': '17:00',
      'endTime': '18:00',
      'session': 'Free Practice 2',
    },
    {
      'date': '14',
      'month': 'Jun',
      'startTime': '12:30',
      'endTime': '13:30',
      'session': 'Free Practice 3',
    },
    {
      'date': '14',
      'month': 'Jun',
      'startTime': '16:00',
      'endTime': '17:00',
      'session': 'Qualifying',
    },
    {
      'date': '15',
      'month': 'Jun',
      'startTime': '14:00',
      'endTime': '16:00',
      'session': 'Race',
    },

    // 11 • Austria (Spielberg)
    {
      'date': '27',
      'month': 'Jun',
      'startTime': '13:30',
      'endTime': '14:30',
      'session': 'Free Practice 1',
    },
    {
      'date': '27',
      'month': 'Jun',
      'startTime': '17:00',
      'endTime': '18:00',
      'session': 'Free Practice 2',
    },
    {
      'date': '28',
      'month': 'Jun',
      'startTime': '12:30',
      'endTime': '13:30',
      'session': 'Free Practice 3',
    },
    {
      'date': '28',
      'month': 'Jun',
      'startTime': '16:00',
      'endTime': '17:00',
      'session': 'Qualifying',
    },
    {
      'date': '29',
      'month': 'Jun',
      'startTime': '15:00',
      'endTime': '17:00',
      'session': 'Race',
    },

    // 12 • Great Britain (Silverstone)
    {
      'date': '04',
      'month': 'Jul',
      'startTime': '12:30',
      'endTime': '13:30',
      'session': 'Free Practice 1',
    },
    {
      'date': '04',
      'month': 'Jul',
      'startTime': '16:00',
      'endTime': '17:00',
      'session': 'Free Practice 2',
    },
    {
      'date': '05',
      'month': 'Jul',
      'startTime': '11:30',
      'endTime': '12:30',
      'session': 'Free Practice 3',
    },
    {
      'date': '05',
      'month': 'Jul',
      'startTime': '15:00',
      'endTime': '16:00',
      'session': 'Qualifying',
    },
    {
      'date': '06',
      'month': 'Jul',
      'startTime': '15:00',
      'endTime': '17:00',
      'session': 'Race',
    },

    // 13 • Belgium (Spa) – Sprint
    {
      'date': '25',
      'month': 'Jul',
      'startTime': '12:30',
      'endTime': '13:30',
      'session': 'Free Practice 1',
    },
    {
      'date': '25',
      'month': 'Jul',
      'startTime': '16:30',
      'endTime': '17:30',
      'session': 'Sprint Qualifying',
    },
    {
      'date': '26',
      'month': 'Jul',
      'startTime': '12:00',
      'endTime': '12:30',
      'session': 'Sprint',
    },
    {
      'date': '26',
      'month': 'Jul',
      'startTime': '16:00',
      'endTime': '17:00',
      'session': 'Qualifying',
    },
    {
      'date': '27',
      'month': 'Jul',
      'startTime': '15:00',
      'endTime': '17:00',
      'session': 'Race',
    },

    // 14 • Hungary (Budapest)
    {
      'date': '01',
      'month': 'Aug',
      'startTime': '12:30',
      'endTime': '13:30',
      'session': 'Free Practice 1',
    },
    {
      'date': '01',
      'month': 'Aug',
      'startTime': '16:00',
      'endTime': '17:00',
      'session': 'Free Practice 2',
    },
    {
      'date': '02',
      'month': 'Aug',
      'startTime': '11:30',
      'endTime': '12:30',
      'session': 'Free Practice 3',
    },
    {
      'date': '02',
      'month': 'Aug',
      'startTime': '16:00',
      'endTime': '17:00',
      'session': 'Qualifying',
    },
    {
      'date': '03',
      'month': 'Aug',
      'startTime': '14:00',
      'endTime': '16:00',
      'session': 'Race',
    },

    // 15 • Netherlands (Zandvoort)
    {
      'date': '29',
      'month': 'Aug',
      'startTime': '12:30',
      'endTime': '13:30',
      'session': 'Free Practice 1',
    },
    {
      'date': '29',
      'month': 'Aug',
      'startTime': '16:00',
      'endTime': '17:00',
      'session': 'Free Practice 2',
    },
    {
      'date': '30',
      'month': 'Aug',
      'startTime': '11:30',
      'endTime': '12:30',
      'session': 'Free Practice 3',
    },
    {
      'date': '30',
      'month': 'Aug',
      'startTime': '15:00',
      'endTime': '16:00',
      'session': 'Qualifying',
    },
    {
      'date': '31',
      'month': 'Aug',
      'startTime': '14:00',
      'endTime': '16:00',
      'session': 'Race',
    },

    // 16 • Italy (Monza)
    {
      'date': '05',
      'month': 'Sep',
      'startTime': '13:30',
      'endTime': '14:30',
      'session': 'Free Practice 1',
    },
    {
      'date': '05',
      'month': 'Sep',
      'startTime': '17:00',
      'endTime': '18:00',
      'session': 'Free Practice 2',
    },
    {
      'date': '06',
      'month': 'Sep',
      'startTime': '12:30',
      'endTime': '13:30',
      'session': 'Free Practice 3',
    },
    {
      'date': '06',
      'month': 'Sep',
      'startTime': '16:00',
      'endTime': '17:00',
      'session': 'Qualifying',
    },
    {
      'date': '07',
      'month': 'Sep',
      'startTime': '14:00',
      'endTime': '16:00',
      'session': 'Race',
    },

    // 17 • Azerbaijan (Baku)
    {
      'date': '19',
      'month': 'Sep',
      'startTime': '12:30',
      'endTime': '13:30',
      'session': 'Free Practice 1',
    },
    {
      'date': '19',
      'month': 'Sep',
      'startTime': '16:00',
      'endTime': '17:00',
      'session': 'Free Practice 2',
    },
    {
      'date': '20',
      'month': 'Sep',
      'startTime': '12:30',
      'endTime': '13:30',
      'session': 'Free Practice 3',
    },
    {
      'date': '20',
      'month': 'Sep',
      'startTime': '16:00',
      'endTime': '17:00',
      'session': 'Qualifying',
    },
    {
      'date': '21',
      'month': 'Sep',
      'startTime': '12:00',
      'endTime': '14:00',
      'session': 'Race',
    },

    // 18 • Singapore
    {
      'date': '03',
      'month': 'Oct',
      'startTime': '17:30',
      'endTime': '18:30',
      'session': 'Free Practice 1',
    },
    {
      'date': '03',
      'month': 'Oct',
      'startTime': '21:00',
      'endTime': '22:00',
      'session': 'Free Practice 2',
    },
    {
      'date': '04',
      'month': 'Oct',
      'startTime': '10:30',
      'endTime': '11:30',
      'session': 'Free Practice 3',
    },
    {
      'date': '04',
      'month': 'Oct',
      'startTime': '14:00',
      'endTime': '15:00',
      'session': 'Qualifying',
    },
    {
      'date': '05',
      'month': 'Oct',
      'startTime': '20:00',
      'endTime': '22:00',
      'session': 'Race',
    },

    // 19 • USA – Austin (Sprint)
    {
      'date': '17',
      'month': 'Oct',
      'startTime': '12:30',
      'endTime': '13:30',
      'session': 'Free Practice 1',
    },
    {
      'date': '17',
      'month': 'Oct',
      'startTime': '16:30',
      'endTime': '17:30',
      'session': 'Sprint Qualifying',
    },
    {
      'date': '18',
      'month': 'Oct',
      'startTime': '12:00',
      'endTime': '12:30',
      'session': 'Sprint',
    },
    {
      'date': '18',
      'month': 'Oct',
      'startTime': '16:00',
      'endTime': '17:00',
      'session': 'Qualifying',
    },
    {
      'date': '19',
      'month': 'Oct',
      'startTime': '14:00',
      'endTime': '16:00',
      'session': 'Race',
    },

    // 20 • Mexico City
    {
      'date': '24',
      'month': 'Oct',
      'startTime': '19:30',
      'endTime': '20:30',
      'session': 'Free Practice 1',
    },
    {
      'date': '24',
      'month': 'Oct',
      'startTime': '23:00',
      'endTime': '00:00',
      'session': 'Free Practice 2',
    },
    {
      'date': '25',
      'month': 'Oct',
      'startTime': '18:30',
      'endTime': '19:30',
      'session': 'Free Practice 3',
    },
    {
      'date': '25',
      'month': 'Oct',
      'startTime': '22:00',
      'endTime': '23:00',
      'session': 'Qualifying',
    },
    {
      'date': '26',
      'month': 'Oct',
      'startTime': '20:00',
      'endTime': '22:00',
      'session': 'Race',
    },

    // 21 • Brazil – São Paulo (Sprint)
    {
      'date': '07',
      'month': 'Nov',
      'startTime': '14:30',
      'endTime': '15:30',
      'session': 'Free Practice 1',
    },
    {
      'date': '07',
      'month': 'Nov',
      'startTime': '18:30',
      'endTime': '19:30',
      'session': 'Sprint Qualifying',
    },
    {
      'date': '08',
      'month': 'Nov',
      'startTime': '14:00',
      'endTime': '14:30',
      'session': 'Sprint',
    },
    {
      'date': '08',
      'month': 'Nov',
      'startTime': '18:00',
      'endTime': '19:00',
      'session': 'Qualifying',
    },
    {
      'date': '09',
      'month': 'Nov',
      'startTime': '17:00',
      'endTime': '19:00',
      'session': 'Race',
    },

    // 22 • Las Vegas
    {
      'date': '21',
      'month': 'Nov',
      'startTime': '00:30',
      'endTime': '01:30',
      'session': 'Free Practice 1',
    },
    {
      'date': '21',
      'month': 'Nov',
      'startTime': '04:00',
      'endTime': '05:00',
      'session': 'Free Practice 2',
    },
    {
      'date': '22',
      'month': 'Nov',
      'startTime': '00:30',
      'endTime': '01:30',
      'session': 'Free Practice 3',
    },
    {
      'date': '22',
      'month': 'Nov',
      'startTime': '04:00',
      'endTime': '05:00',
      'session': 'Qualifying',
    },
    {
      'date': '23',
      'month': 'Nov',
      'startTime': '04:00',
      'endTime': '06:00',
      'session': 'Race',
    },

    // 23 • Qatar – Lusail (Sprint)
    {
      'date': '28',
      'month': 'Nov',
      'startTime': '13:30',
      'endTime': '14:30',
      'session': 'Free Practice 1',
    },
    {
      'date': '28',
      'month': 'Nov',
      'startTime': '17:30',
      'endTime': '18:30',
      'session': 'Sprint Qualifying',
    },
    {
      'date': '29',
      'month': 'Nov',
      'startTime': '14:00',
      'endTime': '14:30',
      'session': 'Sprint',
    },
    {
      'date': '29',
      'month': 'Nov',
      'startTime': '18:00',
      'endTime': '19:00',
      'session': 'Qualifying',
    },
    {
      'date': '30',
      'month': 'Nov',
      'startTime': '16:00',
      'endTime': '18:00',
      'session': 'Race',
    },

    // 24 • Abu Dhabi – Yas Marina
    {
      'date': '05',
      'month': 'Dec',
      'startTime': '09:30',
      'endTime': '10:30',
      'session': 'Free Practice 1',
    },
    {
      'date': '05',
      'month': 'Dec',
      'startTime': '13:00',
      'endTime': '14:00',
      'session': 'Free Practice 2',
    },
    {
      'date': '06',
      'month': 'Dec',
      'startTime': '10:30',
      'endTime': '11:30',
      'session': 'Free Practice 3',
    },
    {
      'date': '06',
      'month': 'Dec',
      'startTime': '14:00',
      'endTime': '15:00',
      'session': 'Qualifying',
    },
    {
      'date': '07',
      'month': 'Dec',
      'startTime': '13:00',
      'endTime': '15:00',
      'session': 'Race',
    },
  ];
}

final scheduleMap = {
  1: [0, 1, 2, 3, 4],
  2: [5, 6, 7, 8, 9, 10],
  3: [11, 12, 13, 14, 15],
  4: [16, 17, 18, 19, 20],
  5: [21, 22, 23, 24, 25],
  6: [26, 27, 28, 29, 30],
  7: [31, 32, 33, 34, 35],
  8: [36, 37, 38, 39, 40],
  9: [41, 42, 43, 44, 45],
  10: [46, 47, 48, 49, 50],
  11: [51, 52, 53, 54, 55],
  12: [56, 57, 58, 59, 60],
  13: [61, 62, 63, 64, 65],
  14: [66, 67, 68, 69, 70],
  15: [71, 72, 73, 74, 75],
  16: [76, 77, 78, 79, 80],
  17: [81, 82, 83, 84, 85],
  18: [86, 87, 88, 89, 90],
  19: [91, 92, 93, 94, 95],
  20: [96, 97, 98, 99, 100],
  21: [101, 102, 103, 104, 105],
  22: [106, 107, 108, 109, 110],
  23: [111, 112, 113, 114, 115],
  24: [116, 117, 118, 119, 120],
};
